/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hn.jm.poo.p1;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class frmSegundo extends javax.swing.JFrame {

    private int nota1;

    /**
     * Creates new form frmSegundo
     */
    public frmSegundo() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblClase = new javax.swing.JLabel();
        txtClase = new javax.swing.JTextField();
        txtNo = new javax.swing.JLabel();
        lblNo1 = new javax.swing.JLabel();
        lblNota3 = new javax.swing.JLabel();
        txtNota4 = new javax.swing.JTextField();
        txtNota1 = new javax.swing.JTextField();
        txtNota3 = new javax.swing.JTextField();
        lblNotaFinal = new javax.swing.JLabel();
        txtNotaFinal = new javax.swing.JTextField();
        txtCalcular = new javax.swing.JButton();
        chkPeperoni = new javax.swing.JCheckBox();
        chkOrilladequeso = new javax.swing.JCheckBox();
        chkHongos = new javax.swing.JCheckBox();
        chkJamon = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BIENVENIDO AL SISTEMA DE CALCULAR");
        setBackground(new java.awt.Color(51, 0, 153));

        lblClase.setText("Clase");

        txtClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaseActionPerformed(evt);
            }
        });

        txtNo.setText("Nota1");

        lblNo1.setText("Nota2");

        lblNota3.setText("Nota3");

        lblNotaFinal.setText("Notal Final");

        txtNotaFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNotaFinalActionPerformed(evt);
            }
        });

        txtCalcular.setText("Calcular");
        txtCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCalcularActionPerformed(evt);
            }
        });

        chkPeperoni.setText("Peperoni");
        chkPeperoni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPeperoniActionPerformed(evt);
            }
        });

        chkOrilladequeso.setText("Orilla De Queso");

        chkHongos.setText("Hongos");

        chkJamon.setText("Jamon");
        chkJamon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkJamonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkPeperoni)
                    .addComponent(chkOrilladequeso)
                    .addComponent(txtCalcular)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNo1)
                                .addComponent(lblNota3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNota1)
                                .addComponent(txtNota3)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtNo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNota4))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblNotaFinal)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNotaFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblClase, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtClase, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chkHongos)
                    .addComponent(chkJamon))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClase, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNo)
                    .addComponent(txtNota4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNo1)
                    .addComponent(txtNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNota3)
                    .addComponent(txtNota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNotaFinal)
                    .addComponent(txtNotaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtCalcular)
                .addGap(21, 21, 21)
                .addComponent(chkPeperoni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkOrilladequeso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkJamon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkHongos)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaseActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtClaseActionPerformed

    private void txtCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCalcularActionPerformed
        // TODO add your handling code here:
        int notal, nota2, nota3;
        double promedio = 0;
        try {
            nota1 = Integer.parseInt(txtNota4.getText());
            nota2 = Integer.parseInt(txtNota1.getText());
            nota3 = Integer.parseInt(txtNota3.getText());
            if (nota1<0 || nota2<0 || nota3<0 ) {
                throw new Exception("Nota 1 debe estar 0 y 100");
            }
            promedio = (nota1 + nota2 + nota3) / 3;
            txtNotaFinal.setText(String.valueOf(promedio));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR: " + e.getMessage());
        }
    }//GEN-LAST:event_txtCalcularActionPerformed

    private void txtNotaFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNotaFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNotaFinalActionPerformed

    private void chkJamonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkJamonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkJamonActionPerformed

    private void chkPeperoniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPeperoniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkPeperoniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSegundo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSegundo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSegundo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSegundo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSegundo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkHongos;
    private javax.swing.JCheckBox chkJamon;
    private javax.swing.JCheckBox chkOrilladequeso;
    private javax.swing.JCheckBox chkPeperoni;
    private javax.swing.JLabel lblClase;
    private javax.swing.JLabel lblNo1;
    private javax.swing.JLabel lblNota3;
    private javax.swing.JLabel lblNotaFinal;
    private javax.swing.JButton txtCalcular;
    private javax.swing.JTextField txtClase;
    private javax.swing.JLabel txtNo;
    private javax.swing.JTextField txtNota1;
    private javax.swing.JTextField txtNota3;
    private javax.swing.JTextField txtNota4;
    private javax.swing.JTextField txtNotaFinal;
    // End of variables declaration//GEN-END:variables
}
